name: genericbro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_typeahead: ^4.8.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/Swecha_Logo_English.png
    - assets/images/logoapp.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logoapp.png"
 
dependency_overrides:
  sign_in_with_apple: ^7.0.1
  sign_in_with_apple_platform_interface: ^2.0.0
  sign_in_with_apple_web: ^3.0.0
  flutter_keyboard_visibility: ^6.0.0
